### PR TITLE
fixes for IL2CPP

### LINKED ISSUE #286: Calling NetManager.Start in dedicated server using IL2CPP throws exception
Calling NetManager.Start in a dedicated server build with IL2CPP option causes exception, see below:

```csharp
ArgumentException: Value does not fall within the expected range.
  at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, System.Int32 optionValue) [0x00000] in <00000000000000000000000000000000>:0
  at System.Net.Sockets.Socket.set_ExclusiveAddressUse (System.Boolean value) [0x00000] in <00000000000000000000000000000000>:0
  at Core.Thirdparty.LiteNetLib.NetSocket.BindSocket (System.Net.Sockets.Socket socket, System.Net.IPEndPoint ep, System.Boolean reuseAddress) [0x00000] in <00000000000000000000000000000000>:0
  at Core.Thirdparty.LiteNetLib.NetSocket.Bind (System.Net.IPAddress addressIPv4, System.Net.IPAddress addressIPv6, System.Int32 port, System.Boolean reuseAddress) [0x00000] in <00000000000000000000000000000000>:0
  at Core.Thirdparty.LiteNetLib.NetManager.Start (System.Net.IPAddress addressIPv4, System.Net.IPAddress addressIPv6, System.Int32 port) [0x00000] in <00000000000000000000000000000000>:0
```

How to reproduce:
1. Create a script which calls NetManager.Start(...).
2. Set script backend to "IL2CPP", Script Runtime Version to ".Net 4.x Equivalent" and Api Compatibility to ".Net 4.x".
3. Go to Build Settings and press Build.
4. Run the created build with argument "-batchmode -nographics".
5. Watch the exception come.

I have tried to make IL2CPP to not strip the assemblies System and System.Core by creating a link.xml file under Assets and added following:
``` xml
<linker>
    <assembly fullname="System.Core" preserve="all"/>
    <assembly fullname="Systeme" preserve="all"/>
</linker>
```

**Library version**: commit id (000563009cd507d56855d865512df18e369c5aa4)

**Framework**: Unity, NET Framework

**OS**: Windows

### PR DESCRIPTION
**Pull request by c6burns**
This PR is from here: https://github.com/MichalPetryka/LiteNetLib/tree/patch-3

Github is throwing 500 errors when trying to PR directly from there

fixes #286

### CODE REVIEW

File: LiteNetLib/NetSocket.cs [hunk 1]
```diff
@@ -38,8 +38,11 @@ public short Ttl
 
         static NetSocket()
         {
-#if DISABLE_IPV6
+#if DISABLE_IPV6 || (ENABLE_IL2CPP && !UNITY_2018_3_OR_NEWER)
             IPv6Support = false;
+#elif ENABLE_IL2CPP && UNITY_2018_3_OR_NEWER
+            string version = Application.unityVersion;
+            IPv6Support = Socket.SupportsIPv6 && int.Parse(version.Remove(version.IndexOf('f')).Split('.')[2]) >= 6;;
```
Comment (MichalPetryka) [inline LiteNetLib/NetSocket.cs]: Crappy code, but needed, since IPv6 works with IL2CPP only with Unity 2018.3.6f1

**Comment by RevenantX** [comment]
Oh Thanks) But i remember it worked some time ago (on IOS)...

File: LiteNetLib/NetSocket.cs (hunk 1 above)
Comment (xmedeko) [reply LiteNetLib/NetSocket.cs]: What about Unity 2019 and newer? I think this check would not pass.
